import { ScheduleType } from "./ScheduleItem";
import { Student, StudentType } from "./Student";

export interface ProfileType {
  id: string;
  method: string; // (Online, Offline)
  registrationDate: string;
  approvedDate: string;
  rejectedDate: string;
  registrationMethod: string;
  status: string; //(pending, approved, payment, successful, rejected)
  studentInfor: StudentType;
}

export interface Profile {
  id: string;
  method: string; // (Online, Offline)
  registrationDate: string;
  approvedDate: string;
  rejectedDate: string;
  registrationMethod: string;
  status: string; //(pending, approved, payment, successful, rejected)
  studentInfor: Student;
  scheduleInfor: ScheduleType[];

  scoreOverall: string;
  receiveDate: string;
  location: string;
}

export const mockRegistrations: Profile[] = [
  {
    id: "reg001",
    method: "Online",
    registrationDate: "2025-03-01",
    approvedDate: "",
    rejectedDate: "",
    registrationMethod: "Online",
    status: "pending",
    studentInfor: {
      personalData: {
        name: "Nguyễn Văn A",
        phone: "0909123456",
        gender: "Nam",
        birthDate: "2000-01-15",
        licenseType: "B1",
        email: "vana@gmail.com",
        healthCheckDocURL: "/healthcheck/b.jpg",
      },
      personalImgData: {
        avatar: "/avatars/a.png",
        cardImgFront: "/cards/front_a.png",
        cardImgBack: "/cards/back_a.png",
      },
      chooseData: {
        course: {
          id: "course001",
          name: "Khóa học B1 - Sáng",
          typeOfLicense: "B1",
          examDate: "2025-05-20",
          startDate: "2025-04-30",
          endDate: "2025-05-30",
          registeredCount: 15,
          maxStudents: 30,
        },
        healthCheck: {
          id: "1",
          name: "Khám sức khỏe tổng quát",
          date: "2025-06-15",
          address: "Bệnh viện ABC, Đường XYZ, TP.HCM",
        },
      },
    },
    scheduleInfor: [
      {
        id: "schedule001",
        courseId: "course001",
        typeOfLicense: "B1",
        type: "LyThuyet",
        date: "2025-04-30",
        startTime: "08:00",
        endTime: "10:00",
        location: "Phòng học A1",
        teacher: "Nguyễn Văn T",
      },
      {
        id: "schedule002",
        courseId: "course001",
        typeOfLicense: "B1",

        type: "ThucHanh",
        date: "2025-05-02",
        startTime: "08:00",
        endTime: "10:00",
        location: "Phòng học A1",
        teacher: "Nguyễn Văn T",
      },
    ],
    scoreOverall: "",
    receiveDate: "",
    location: "",
  },
  {
    id: "reg002",
    method: "Online",
    registrationDate: "2025-03-05",
    approvedDate: "2025-03-10",
    rejectedDate: "",
    registrationMethod: "Offline",
    status: "successful",
    studentInfor: {
      personalData: {
        name: "Trần Thị B",
        phone: "0912345678",
        gender: "Nữ",
        birthDate: "1998-09-12",
        licenseType: "B2",
        email: "tranb@gmail.com",
        healthCheckDocURL: "/healthcheck/b.jpg",
      },
      personalImgData: {
        avatar: "/avatars/b.png",
        cardImgFront: "/cards/front_b.png",
        cardImgBack: "/cards/back_b.png",
      },
      chooseData: {
        course: {
          id: "course002",
          name: "Khóa học B2 - Chiều",
          examDate: "2025-06-10",
          typeOfLicense: "B2",
          startDate: "2025-05-20",
          endDate: "2025-06-20",
          registeredCount: 20,
          maxStudents: 25,
        },
        healthCheck: {
          id: "2",
          name: "Khám sức khỏe định kỳ",
          date: "2025-07-20",
          address: "Phòng khám XYZ, Đường ABC, Hà Nội",
        },
      },
    },
    scheduleInfor: [
      {
        id: "schedule001",
        courseId: "course001",
        typeOfLicense: "A1",

        type: "LyThuyet",
        date: "2025-04-30",
        startTime: "08:00",
        endTime: "10:00",
        location: "Phòng học A1",
        teacher: "Nguyễn Văn T",
      },
      {
        id: "schedule002",
        type: "ThucHanh",
        typeOfLicense: "A2",

        courseId: "course001",
        date: "2025-05-02",
        startTime: "08:00",
        endTime: "10:00",
        location: "Phòng học A1",
        teacher: "Nguyễn Văn T",
      },
    ],
    scoreOverall: "",
    receiveDate: "",
    location: "",
  },
  {
    id: "reg003",
    method: "Offline",
    registrationDate: "2025-03-07",
    approvedDate: "",
    rejectedDate: "2025-03-09",
    registrationMethod: "Online",
    status: "rejected",
    studentInfor: {
      personalData: {
        name: "Lê Văn C",
        phone: "0922123456",
        gender: "Nam",
        birthDate: "1995-05-20",
        licenseType: "C",
        healthCheckDocURL: "/healthcheck/b.jpg",
      },
      personalImgData: {
        avatar: "/avatars/c.png",
        cardImgFront: "/cards/front_c.png",
        cardImgBack: "/cards/back_c.png",
      },
      chooseData: {
        course: {
          id: "course003",
          name: "Khóa học C - Tối",
          examDate: "2025-06-25",
          typeOfLicense: "A1",
          startDate: "2025-06-01",
          endDate: "2025-07-01",
          registeredCount: 10,
          maxStudents: 20,
        },
        healthCheck: {
          id: "3",
          name: "Khám sức khỏe chuyên khoa",
          date: "2025-08-10",
          address: "Bệnh viện DEF, Đường UVW, Đà Nẵng",
        },
      },
    },
    scheduleInfor: [
      {
        id: "schedule001",
        courseId: "course001",
        type: "LyThuyet",
        typeOfLicense: "B1",

        date: "2025-04-30",
        startTime: "08:00",
        endTime: "10:00",
        location: "Phòng học A1",
        teacher: "Nguyễn Văn T",
      },
      {
        id: "schedule002",
        courseId: "course001",
        typeOfLicense: "A2",

        type: "ThucHanh",
        date: "2025-05-02",
        startTime: "08:00",
        endTime: "10:00",
        location: "Phòng học A1",
        teacher: "Nguyễn Văn T",
      },
    ],
    scoreOverall: "",
    receiveDate: "",
    location: "",
  },
  {
    id: "reg004",
    method: "Offline",
    registrationDate: "2025-03-08",
    approvedDate: "2025-03-09",
    rejectedDate: "",
    registrationMethod: "Online",
    status: "payment",
    studentInfor: {
      personalData: {
        name: "Phạm Thị D",
        phone: "0987456123",
        gender: "Nữ",
        birthDate: "2001-02-02",
        licenseType: "B1",
        email: "pham.d@example.com",
        healthCheckDocURL: "/healthcheck/b.jpg",
      },
      personalImgData: {
        avatar: "/avatars/d.png",
        cardImgFront: "/cards/front_d.png",
        cardImgBack: "/cards/back_d.png",
      },
      chooseData: {
        course: {
          id: "course004",
          name: "Khóa học B1 - Tối",
          examDate: "2025-07-01",
          typeOfLicense: "B1",
          startDate: "2025-06-15",
          endDate: "2025-07-01",
          registeredCount: 18,
          maxStudents: 30,
        },
        healthCheck: {
          id: "2",
          name: "Khám sức khỏe định kỳ",
          date: "2025-07-20",
          address: "Phòng khám XYZ, Đường ABC, Hà Nội",
        },
      },
    },
    scheduleInfor: [
      {
        id: "schedule001",
        courseId: "course001",
        type: "LyThuyet",
        typeOfLicense: "A1",
        date: "2025-04-30",
        startTime: "08:00",
        endTime: "10:00",
        location: "Phòng học A1",
        teacher: "Nguyễn Văn T",
      },
      {
        id: "schedule002",
        courseId: "course001",
        typeOfLicense: "A1",
        type: "ThucHanh",
        date: "2025-05-02",
        startTime: "08:00",
        endTime: "10:00",
        location: "Phòng học A1",
        teacher: "Nguyễn Văn T",
      },
    ],
    scoreOverall: "",
    receiveDate: "",
    location: "",
  },
  {
    id: "reg005",
    method: "Offline",
    registrationDate: "2025-03-10",
    approvedDate: "2025-03-11",
    rejectedDate: "",
    registrationMethod: "Offline",
    status: "successful",
    studentInfor: {
      personalData: {
        name: "Đỗ Văn E",
        phone: "0977888999",
        gender: "Nam",
        birthDate: "1999-07-07",
        licenseType: "B2",
        healthCheckDocURL: "/healthcheck/b.jpg",
      },
      personalImgData: {
        avatar: "/avatars/e.png",
        cardImgFront: "/cards/front_e.png",
        cardImgBack: "/cards/back_e.png",
      },
      chooseData: {
        course: {
          id: "course005",
          name: "Khóa học B2 - Sáng",
          examDate: "2025-07-15",
          typeOfLicense: "B2",
          startDate: "2025-06-01",
          endDate: "2025-07-01",
          registeredCount: 25,
          maxStudents: 25,
        },
        healthCheck: {
          id: "1",
          name: "Khám sức khỏe tổng quát",
          date: "2025-06-15",
          address: "Bệnh viện ABC, Đường XYZ, TP.HCM",
        },
      },
    },
    scheduleInfor: [
      {
        id: "schedule001",
        courseId: "course001",
        typeOfLicense: "A1",

        type: "LyThuyet",
        date: "2025-04-30",
        startTime: "08:00",
        endTime: "10:00",
        location: "Phòng học A1",
        teacher: "Nguyễn Văn T",
      },
      {
        id: "schedule002",
        courseId: "course001",
        typeOfLicense: "A1",
        date: "2025-05-02",
        type: "ThucHanh",
        startTime: "08:00",
        endTime: "10:00",
        location: "Phòng học A1",
        teacher: "Nguyễn Văn T",
      },
    ],
    scoreOverall: "",
    receiveDate: "",
    location: "",
  },
  {
    id: "reg006",
    method: "Offline",
    registrationDate: "2025-03-12",
    approvedDate: "",
    rejectedDate: "",
    registrationMethod: "Online",
    status: "pending",
    studentInfor: {
      personalData: {
        name: "Lý Thị F",
        phone: "0933222111",
        gender: "Nữ",
        birthDate: "2002-08-20",
        licenseType: "C",
        email: "ly.f@example.com",
        healthCheckDocURL: "/healthcheck/b.jpg",
      },
      personalImgData: {
        avatar: "/avatars/f.png",
        cardImgFront: "/cards/front_f.png",
        cardImgBack: "/cards/back_f.png",
      },
      chooseData: {
        course: {
          id: "course006",
          name: "Khóa học C - Chiều",
          examDate: "2025-08-10",
          typeOfLicense: "C",
          startDate: "2025-07-20",
          endDate: "2025-08-01",
          registeredCount: 12,
          maxStudents: 20,
        },
        healthCheck: {
          id: "3",
          name: "Khám sức khỏe chuyên khoa",
          date: "2025-08-10",
          address: "Bệnh viện DEF, Đường UVW, Đà Nẵng",
        },
      },
    },
    scheduleInfor: [
      {
        id: "schedule001",
        courseId: "course001",
        typeOfLicense: "A1",
        type: "LyThuyet",
        date: "2025-04-30",
        startTime: "08:00",
        endTime: "10:00",
        location: "Phòng học A1",
        teacher: "Nguyễn Văn T",
      },
      {
        id: "schedule002",
        courseId: "course001",
        typeOfLicense: "A1",
        type: "ThucHanh",
        date: "2025-05-02",
        startTime: "08:00",
        endTime: "10:00",
        location: "Phòng học A1",
        teacher: "Nguyễn Văn T",
      },
    ],
    scoreOverall: "",
    receiveDate: "",
    location: "",
  },
  {
    id: "reg007",
    method: "Online",
    registrationDate: "2025-03-13",
    approvedDate: "2025-03-14",
    rejectedDate: "",
    registrationMethod: "Offline",
    status: "payment",
    studentInfor: {
      personalData: {
        name: "Ngô Văn G",
        phone: "0955667788",
        gender: "Nam",
        birthDate: "1997-12-10",
        licenseType: "B1",
        healthCheckDocURL: "/healthcheck/b.jpg",
      },
      personalImgData: {
        avatar: "/avatars/g.png",
        cardImgFront: "/cards/front_g.png",
        cardImgBack: "/cards/back_g.png",
      },
      chooseData: {
        course: {
          id: "course006",
          name: "Khóa học C - Chiều",
          examDate: "2025-08-10",
          typeOfLicense: "A2",
          startDate: "2025-07-20",
          endDate: "2025-08-01",
          registeredCount: 12,
          maxStudents: 20,
        },
        healthCheck: {
          id: "3",
          name: "Khám sức khỏe chuyên khoa",
          date: "2025-08-10",
          address: "Bệnh viện DEF, Đường UVW, Đà Nẵng",
        },
      },
    },
    scheduleInfor: [
      {
        id: "schedule001",
        courseId: "course001",
        type: "LyThuyet",
        typeOfLicense: "A1",
        date: "2025-04-30",
        startTime: "08:00",
        endTime: "10:00",
        location: "Phòng học A1",
        teacher: "Nguyễn Văn T",
      },
      {
        id: "schedule002",
        courseId: "course001",
        typeOfLicense: "A1",
        type: "ThucHanh",
        date: "2025-05-02",
        startTime: "08:00",
        endTime: "10:00",
        location: "Phòng học A1",
        teacher: "Nguyễn Văn T",
      },
    ],
    scoreOverall: "",
    receiveDate: "",
    location: "",
  },
  {
    id: "reg008",
    method: "Online",
    registrationDate: "2025-03-14",
    approvedDate: "",
    rejectedDate: "2025-03-15",
    registrationMethod: "Online",
    status: "successful",
    studentInfor: {
      personalData: {
        name: "Hồ Thị H",
        phone: "0944332211",
        gender: "Nữ",
        birthDate: "2000-04-04",
        licenseType: "B2",
        email: "hoh@example.com",
        healthCheckDocURL: "/healthcheck/b.jpg",
      },
      personalImgData: {
        avatar: "/avatars/h.png",
        cardImgFront: "/cards/front_h.png",
        cardImgBack: "/cards/back_h.png",
      },
      chooseData: {
        course: {
          id: "course006",
          name: "Khóa học C - Chiều",
          examDate: "2025-08-10",
          typeOfLicense: "A2",
          startDate: "2025-07-20",
          endDate: "2025-08-01",
          registeredCount: 12,
          maxStudents: 20,
        },
        healthCheck: {
          id: "3",
          name: "Khám sức khỏe chuyên khoa",
          date: "2025-08-10",
          address: "Bệnh viện DEF, Đường UVW, Đà Nẵng",
        },
      },
    },
    scheduleInfor: [
      {
        id: "schedule001",
        type: "LyThuyet",
        courseId: "course001",
        typeOfLicense: "A1",
        date: "2025-04-30",
        startTime: "08:00",
        endTime: "10:00",
        location: "Phòng học A1",
        teacher: "Nguyễn Văn T",
      },
      {
        id: "schedule002",
        courseId: "course001",
        typeOfLicense: "A1",
        type: "ThucHanh",
        date: "2025-05-02",
        startTime: "08:00",
        endTime: "10:00",
        location: "Phòng học A1",
        teacher: "Nguyễn Văn T",
      },
    ],
    scoreOverall: "",
    receiveDate: "",
    location: "",
  },
  {
    id: "reg009",
    method: "Online",
    registrationDate: "2025-03-15",
    approvedDate: "2025-03-16",
    rejectedDate: "",
    registrationMethod: "Online",
    status: "payment",
    studentInfor: {
      personalData: {
        name: "Vũ Văn I",
        phone: "0933999000",
        gender: "Nam",
        birthDate: "1996-06-06",
        licenseType: "C",
        email: "vui@example.com",
        healthCheckDocURL: "/healthcheck/b.jpg",
      },
      personalImgData: {
        avatar: "/avatars/i.png",
        cardImgFront: "/cards/front_i.png",
        cardImgBack: "/cards/back_i.png",
      },
      chooseData: {
        course: {
          id: "course006",
          name: "Khóa học C - Chiều",
          examDate: "2025-08-10",
          typeOfLicense: "A1",
          startDate: "2025-07-20",
          endDate: "2025-08-01",
          registeredCount: 12,
          maxStudents: 20,
        },
        healthCheck: {
          id: "3",
          name: "Khám sức khỏe chuyên khoa",
          date: "2025-08-10",
          address: "Bệnh viện DEF, Đường UVW, Đà Nẵng",
        },
      },
    },
    scheduleInfor: [
      {
        id: "schedule001",
        courseId: "course001",
        typeOfLicense: "A1",
        type: "LyThuyet",
        date: "2025-04-30",
        startTime: "08:00",
        endTime: "10:00",
        location: "Phòng học A1",
        teacher: "Nguyễn Văn T",
      },
      {
        id: "schedule002",
        courseId: "course001",
        type: "ThucHanh",
        typeOfLicense: "A1",
        date: "2025-05-02",
        startTime: "08:00",
        endTime: "10:00",
        location: "Phòng học A1",
        teacher: "Nguyễn Văn T",
      },
    ],
    scoreOverall: "",
    receiveDate: "",
    location: "",
  },
  {
    id: "reg010",
    method: "Offline",
    registrationDate: "2025-03-16",
    approvedDate: "2025-03-17",
    rejectedDate: "",
    registrationMethod: "Offline",
    status: "successful",
    studentInfor: {
      personalData: {
        name: "Lê Thị J",
        phone: "0966554433",
        gender: "Nữ",
        birthDate: "1994-11-11",
        licenseType: "B1",
        healthCheckDocURL: "/healthcheck/b.jpg",
      },
      personalImgData: {
        avatar: "/avatars/j.png",
        cardImgFront: "/cards/front_j.png",
        cardImgBack: "/cards/back_j.png",
      },
      chooseData: {
        course: {
          id: "course006",
          name: "Khóa học C - Chiều",
          examDate: "2025-08-10",
          typeOfLicense: "A2",
          startDate: "2025-07-20",
          endDate: "2025-08-01",
          registeredCount: 12,
          maxStudents: 20,
        },
        healthCheck: {
          id: "3",
          name: "Khám sức khỏe chuyên khoa",
          date: "2025-08-10",
          address: "Bệnh viện DEF, Đường UVW, Đà Nẵng",
        },
      },
    },
    scheduleInfor: [
      {
        id: "schedule001",
        courseId: "course001",
        typeOfLicense: "A1",
        type: "LyThuyet",
        date: "2025-04-30",
        startTime: "08:00",
        endTime: "10:00",
        location: "Phòng học A1",
        teacher: "Nguyễn Văn T",
      },
      {
        id: "schedule002",
        courseId: "course001",
        typeOfLicense: "A1",
        type: "ThucHanh",
        date: "2025-05-02",
        startTime: "08:00",
        endTime: "10:00",
        location: "Phòng học A1",
        teacher: "Nguyễn Văn T",
      },
    ],
    scoreOverall: "",
    receiveDate: "",
    location: "",
  },
];
